# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    commit-message:
      prefix: 'chore'
    ignore:
      - dependency-name: 'semantic-release' # requires upgrade to node v18 (workarounds: https://semantic-release.gitbook.io/semantic-release/support/node-version#recommended-solution); currently storybook breaks on node v18
      - dependency-name: '@storybook/*'
