import { readdirSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ICONS_DIR = join(__dirname, '../src/components/icons')
const OUTPUT_FILE = join(ICONS_DIR, 'types.ts')

const sizes = ['sm', 'md', 'lg', 'other'] as const

function getIconNames(size: string): string[] {
  const dir = join(ICONS_DIR, size)
  return readdirSync(dir)
    .filter(f => f.endsWith('.svg'))
    .map(f => f.replace('.svg', ''))
    .sort()
}

function generateUnionType(name: string, icons: string[]): string {
  if (icons.length === 0) return `export type ${name} = never`
  return `export type ${name} =\n${icons.map(i => `  | '${i}'`).join('\n')}`
}

const iconsBySize = Object.fromEntries(sizes.map(s => [s, getIconNames(s)]))

const output = `// This file is auto-generated by scripts/generate-icon-types.ts
// Do not edit manually. Run \`npm run generate:icon-types\` to regenerate.

${generateUnionType('SmIcon', iconsBySize.sm)}

${generateUnionType('MdIcon', iconsBySize.md)}

${generateUnionType('LgIcon', iconsBySize.lg)}

${generateUnionType('OtherIcon', iconsBySize.other)}

export type IconSize = 'sm' | 'md' | 'lg' | 'other'

export type IconName<S extends IconSize> = S extends 'sm'
  ? SmIcon
  : S extends 'md'
    ? MdIcon
    : S extends 'lg'
      ? LgIcon
      : S extends 'other'
        ? OtherIcon
        : never

export type AnyIcon = SmIcon | MdIcon | LgIcon | OtherIcon
export type AnyIconName = AnyIcon | Uncapitalize<AnyIcon>

type KebabCase<S extends string> = S extends \`\${infer First}\${infer Rest}\`
  ? Rest extends Uncapitalize<Rest>
    ? \`\${Lowercase<First>}\${KebabCase<Rest>}\`
    : \`\${Lowercase<First>}-\${KebabCase<Rest>}\`
  : S

export type SmIconId = \`\${KebabCase<SmIcon>}-sm\`
export type MdIconId = \`\${KebabCase<MdIcon>}-md\`
export type LgIconId = \`\${KebabCase<LgIcon>}-lg\`
export type OtherIconId = \`\${KebabCase<OtherIcon>}-other\`

export type IconIdentifier = SmIconId | MdIconId | LgIconId | OtherIconId
`

writeFileSync(OUTPUT_FILE, output)
console.log(`Generated ${OUTPUT_FILE}`)
console.log(`  sm: ${iconsBySize.sm.length} icons`)
console.log(`  md: ${iconsBySize.md.length} icons`)
console.log(`  lg: ${iconsBySize.lg.length} icons`)
console.log(`  other: ${iconsBySize.other.length} icons`)
