name: Backup repo to S3
on:
  push:
    branches:
      - main
jobs:
  backup_to_codecommit:
    uses: 'archilogic-com/actions/.github/workflows/backup-repo.yml@main'
    with:
      TARGET_REPO_URL: 'honeycomb'
    secrets: inherit
