name: Backup repo to S3
on:
  push:
    branches:
      - main
jobs:
  s3Backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: S3 Backup
        uses: peter-evans/s3-backup@v1
        env:
          ACCESS_KEY_ID: ${{ secrets.BACKUP_AWS_ACCES_KEY }}
          SECRET_ACCESS_KEY: ${{ secrets.BACKUP_AWS_SECRET_ACCESS_KEY }}
          MIRROR_TARGET: ${{ secrets.BACKUP_BUCKET }}/${{ github.repository }}
        with:
          args: --overwrite --remove
